# fly.toml app configuration file generated for swagtask on 2025-05-31T16:29:39+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swagtask'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1


[deploy]
release_command = "sh -c 'echo \"DEBUG_DATABASE_URL_VALUE: $DATABASE_URL\" && migrate -path ./internal/db/migrations -database \"$DATABASE_URL\" up'"