ALTER TABLE sessions
ALTER COLUMN user_id
DROP NOT NULL;

ALTER TABLE tags
ALTER COLUMN created_at
DROP NOT NULL,
ALTER COLUMN updated_at
DROP NOT NULL;

ALTER TABLE tasks
ALTER COLUMN created_at
DROP NOT NULL,
ALTER COLUMN updated_at
DROP NOT NULL,
ALTER COLUMN completed
DROP NOT NULL;

ALTER TABLE users
ALTER COLUMN created_at
DROP NOT NULL,
ALTER COLUMN updated_at
DROP NOT NULL,
ALTER COLUMN path_to_pfp
DROP NOT NULL;

ALTER TABLE vault_user_relations
ALTER COLUMN role
DROP NOT NULL;

ALTER TABLE vaults
ALTER COLUMN created_at
DROP NOT NULL,
ALTER COLUMN updated_at
DROP NOT NULL,
ALTER COLUMN locked
DROP NOT NULL;